name: Push To Dockerhub
on:
  push:
    branches:
      - master
      - main

env:
  DOCKERHUB_USERNAME: zibdie
  MAIN_REPO_NAME: zibdie/tordetector

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        version:
          - { language: "js", dockerfile: "Dockerfile.js", tag: "myuser/tordetector:js" }
          - { language: "py", dockerfile: "Dockerfile.py", tag: "myuser/tordetector:py" }
          - { language: "php", dockerfile: "Dockerfile.php", tag: "myuser/tordetector:php" }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          file: ${{ env.GITHUB_WORKSPACE }}/${{ matrix.version.dockerfile }}
          push: true
          tags: ${{ matrix.version.tag }}
      - name: Update repo description
        if: matrix.version.language == 'py'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ env.MAIN_REPO_NAME }}
          readme-filepath: ./README.md
